### PR TITLE
Views

### PR DESCRIPTION
**Pull request by Gegardus**
Implementing views have been updated layouts for:

- users#index
- users#show
- posts#index
- posts#show.

### CODE REVIEW

**Review by Emmyn5600 — CHANGES_REQUESTED** [review]
Hi @Gegardus 

Good job so far! I know you have worked hard on making this milestone. There are some issues that you still need to work on to go to the next project but you are almost there!

almost-there

## Required Changes :recycle:
image

- [ ] You have implemented only a view for the users, kindly implement the view for the post, comments, and likes added by a user.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!:clap::clap::clap:
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
#### **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Gegardus** [comment]
@Emmyn5600 I have implemented all views. The screenshot you posted has nothing to do with my project at all. Please, kindly, check the link.

**Comment by Gegardus** [comment]
Here are real screenshots:
all-user

user-info

all-posts

user-post

**Comment by bellom** [comment]
Hi @Gegardus, It would have been nice to create a seed file so that the CR or anyone else can easily test your app without having to use the rails console.
And also, you didn't link the user profile to the posts page but you have the routes, it would be nice to navigate by clicking the username.

Example: As shown in the wireframe below, the user should be able to navigate to the list of posts by clicking the user name.
image

This activity has been approved.

**Comment by Gegardus** [comment]
Thank you @bellom

**Pull request merged**
